project:
  type: website
  output-dir: docs

website:
  title: "M4 D250"
  navbar:
    left:
      - href: machine.qmd
        text: Home
  page-navigation: true
format:
  html:
    theme: default
    toc: true
